# Generated by Django 2.1.2 on 2018-12-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.IntegerField()),
                ('UserName', models.CharField(max_length=20)),
                ('UserImgs', models.CharField(max_length=128)),
                ('Age', models.IntegerField()),
                ('Sex', models.IntegerField(default=0)),
                ('UserAutoGraph', models.CharField(max_length=50)),
                ('CreateTime', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
